language: python
sudo: false
python:
  - "3.4"

env:
  global:
    - secure: "unE0HcbJwVkVc70IQJtFHMgTYLdc0YfxjAQVkyf4zUGXJDG1DhGWwbwlmON8x2Xf9EW0633UlAi/AsLrnN6/S6CVLwsUOM2UF90RHeYFeU2+Lau+wlTAxXszAI9IL0T6mczncXWIQwvMWU7RDvtOaQVAmbAgyy9DUjaeEs8ZCIY168t/wN6sny2JoSPqabYOB+LL+gJgIb+JChyRqJ7nxAFeGONKl3AqrJMGL5W9UmfUkPfEPyeytHJmpoqEDQBRIvO3MIfw9Iw4Tmv+MYpxqh42Dj+GcghFlcX88AR5EWmo6Puh2FQNtqjBHbwPPNpjkZtRCz4JVvDXLnQkEyqV658aiz1q0UkHwUlQpt+GkJpjqCMLa+3rzi3RwVzgTLotC7WRITkL4rUkWoq0Dfb6qKyywVA2EwriU1Tnb7+LtG9TIeKCRp93RPh6v+izsOvBN1rJgaeZY98ROc7iRX3FV+3z0w0uPOlYJYslEERy1QYOmgwP3OJ0WrnpL99BgJfUU+8MzBk71Ll5R5+q4fIyImXPA9wx7DfCZBbD6dZOgPflyYfNpRPtDMDVHht2A7mfj7x4ba+k4s6iHNyc7Pn7ujCqNEMZe1EYAmS+BN7q2OtWkIMB0ZPZvMF2YveRUbNxBTDfiZAwbvkwDqAHo3to+8Pf4epvOY79WiDmHhrMsVQ="
    - secure: "Fd398VFE5zlldVzoCMwdGdteVHbTiGUnitKJdAl4K/B3hxvd+icP36ezRIPpxlGGWFosoqTDR/ikr/WN2AKlzsQARHz8cANvJgZqN0XACzQxiz5pePlmZ6iakAfRxk0jJRwfnowjS1o2AE27jxJTXFVekLR9TSZJCK0tC+QVjcBHAdeXEZYA2S5wgDBIWIPobwrC2M9Ym+mXDM8vJx6TGPaxalmnT5sC4ea2K4+z0/faHPzjOlCnifsdJBW1NnEvIj0lyXEoOiuILakkB4v2XOsHeUl6+pcmKgd05G7EMIvze5rpjLJyGborjVD6bZNYEt72n1Pxli4AoupuzAZSvTTWQTNlY57UUEDWfd+xk2uGySNmYhPWbvc/tecsV5DHapiTBoUqascb/0eu6w2jPx6UWAwGtsu2thNXgxuN4CB+SBinKwwMinsnR3Hkb6kzcKEc0S0ohVzuI/LqNuZWjWam/KvnxY1Z55Sb9A1oe+YJYyaRDJe0U5RW1rVSeKe//8w9CFfvtdIyD22Q06Fhb21i1que8dinxHZjR/xp6CzDMwMjk3SL/3MPOf1BjASaXITs0aMVR6MOm+kjENc0nRFcUadu2QZITB8IUP2jFbY353bfo4YUwWK6yNdsUt5/So1UdYOqT7eaYAyYQcYuLAn2swOd2uMDNPHB4wTskRk="
    - 'AWS_ACCESS_KEY_ID=AKIAJP3DIYUEHRAW7A6A'
    - secure: "IOVIXR/fHCYfi5065qVo55DNuMb/u5iQMTMZn3zV2OAkMLhb5WbyNJhTSUvtdqVjqmw1ay/f36gVmgwyMb4UaLOIZfHbKHb7AYTYZ8ZVOLKFdVkGj8Nfn9XXRwzcsWpPeU2ZvZWAaaPbZKyq0rK2litOxZykJjBmQ80q/XFNbgAHpJOQSdHFSFSyGSox9KeE/uDcEftMK6R/o7FFm+tNWUgrgT0cxjX0YSaFKH/PdlnlVj6/IbUbbEHyQUaF/w1Kv48gwsPDaZ7YZfa9MyrSIksZbbIi+3xXyiXvlADrL9buLgMgIVyAYn5Z4ThKfguyKkz42ShHEAsfSMTcTcInGbjKObD8/S6G7to5yJZsSs7DIkysepToeGXx5wG7ZBn6eGwY5P3dCC6dedFrvsRaS6k0cFMM2QhUFpwFoLh5aZkNlD6BL1aBrhE4mrvypyugOXuU/dGaOLCevqEpyfW+wAO4Aq6vbFToOmPqX0VUY995Om4P7t4OBC0GQN1mZ1QQX8dojkgIVihnWaFY4eJvbWMciZnuo8Nb5CqBzfv2YJ/rCeGnrFSuM1ctdRlOywdL8CG0SuNq5bcJRXm6zpMqkqdOfcRwAtIR5PJ2RHai+ivwq7GmgxCosKuG42+bj69PrhDYAWwDxtGLtD3PnZatBXACnV/fcZH3LFKIyC7if7Y="
    - secure: "pBVA1oGu+P9H+r15ZdKgZgWmfodPMKijQPtJsmjD3oBuB+ZUIAp/r1VJAttbSZTR63x+DNY63htFHsNCWNonFjOxSb5qFnEGWfmhy7qLUEDuPAqZHEu2eDlmAga1qlFQBwKeJrYkUm5VwYrKvyeFmDB2VqHgQZpioRr10x2NpGtokMG9YI4ONW2aryO4HJCbiMp3RVz7YXexvbf9/hqv04gGOlbEqTQCVukR0PC1xD8EHUapYAwgBskDgD/KLB7eTrTZmxYAGRRqdxMNECfiXCbiFyfkq36e2WGLrbNWdD4oGdk2TER4M1zzTQYfnHoIfaWiR8kjssFQPAW5/Sl0q7HejOBPak32dQKeoeMy4Gv0KtsXPSSCgiqxy9307FpQRpWx93syNDtmV8Ajx3PS52B8SRqyVddMa0PYQbmGYJ/OAhofdyutiTnlXMYJE8fPG7t42lExg1KYZbykSG/bGG57IpTwsHdngsgbMdLOeGkBnQ2dqNb2KPR1hHftGtPR6MN1tWdE3xPfuqTVsB89abPWkKaOdeMnpyXav818YZZ1O3oKAJAhNNeGERGTtaR8cwuNEOlaFl2gczgKGYyfqoAtXE29xOFh0ANuSipYjksTq5YWwlD7/kAa2rMcJrYxyf5XxT2BgUKeCRgU2rJ9txPckabwGsH1uaQ7LwnH0jI="
    - secure: "fuyde8SWKB/jm4apu4Uc7uMPrJK3d6qwMx8aasY5UQDqD0PhpRh9Bq/uirH33T6FrgUU8W4GgUnV6j+FEXElk8uHI/yWeSwiWtuPYk3N1nHrcXK4byU6HfNceeN6VakToIS+RCSETdssS/ijb9a3HlZbxQfKvPvQ5xG/5qH01cIxZqoEtfNdxThsy4Xc4jzgepnmapUON1GZ9CM0Mv/2GKaepY9nJ0fpfulag/IEnYt8ld68UEeBWkxGV5bM5xUaBSAJynr74AuTL2PzE/hqXm4vsYWsFi7tW97YLHS724cLJZjMr/UFj/KDTlCDlJwv91+Imkpm2E1MbMw+8SmhfukT18qSIj4g/0NmCcGo4k3Q7ISTs+Wm2vbb4gQXsekOnAC1EjsMWmGHjXnboRirIwxzju1Bm2vQQg/o+5dzfIWHGgjjTky7XsGnMjQg7heHoZsVmdRzLGE9kmP1+4GwW6tdCEeb71rW5HUnVtmICJGAY2oVDXFe+NXTsEXkYMPw02W/4vXfQC+DHzhDBiB+C8KUrPcHnA50T6AEvbJ7cP3pOBljulXDkP5WCeZuSE3W4+scWQFxwSEtXy4jbAAwP82hVnGxx6Ql6QBxvUlO86PETKWabY9jdoUb/4Z9x30uhMXqNg+FjUYKv9JfLKZDMc6AsSaPClZtXyjItNH5XLY="

install:
  - bundle install
  - pip install -U twine
  - make install
  - ./env/bin/pip install coveralls

script:
  - make checkstyle
  - make test
  - make docs

after_success:
  - ./env/bin/coveralls

deploy:
- provider: pypi
  user: marvinpinto
  password:
    secure: etI6uS3Ercc5X4lHYMgoqzdecFBYuwibn7PmtmDFG9573A+r6QldIqfkn5PrDOJGm0Y0PNp7cxGutZ/+4KsyiH9zKr2p1M83Gpuloc8L1ZFxPSzlJQsLK1xaiMT8YbvR9ThLO+ua42Zx3AcFcGANpbeWqYdZ6ELEcWd/a0EkG7RFbhWg99ypaOVQCtap3Wfm88bv0Y586YbmB6r//f3HOvW3VX9ID5BQxVo7NCvqjKsygdqix0bq4wjLQoWohlw4W04ldN7Pba8+uAD+6G7sLit8J1FZQOe6n8t/qhndIBYU7v/jp3KJJMxuEWFfaJ5+gf+d+Ypx56v1e1po+bQ2bEDstjigNhVI4vzSwa4ksUQnr7BggtIO94BzrLNCpYvEJjsKoAjrYSrLbmtUYhW8y13YprW+bJiTFYJQpq1Ly9hZPCaDQ7yfs0kbsaax5XBc5MsT3VD6kq/EwCr3z0ZOidN3QJCts+bPZlH5cC7XnifOiIwySMu/C5DFmuqHffOZ+2vYfKutDUcX2PvbPnvv9P2yINfrAtBAsqeYf1r0jy3TeThASpClvdRstQQCpdrAxKR3L8l23wdjq+SES5O1RNp05K1XMe2oDgycG7epCTIKLYAeb9Ak0Trmkc34CXeEUClI9SXbGfHqdOsMLBgooj1bTTjDOXKtDfk+Y85kwis=
  on:
    tags: true
    repo: marvinpinto/charlesbot
- provider: 'script'
  script: 'bundle exec s3_website push --verbose'
  skip_cleanup: true
  on:
    branch: 'master'
    repo: 'marvinpinto/charlesbot'

after_deploy:
  - ./scripts/trigger_quayio.sh

notifications:
  email: false
  irc:
    - secure: "Y5ZXefNfyouSSCyD+A6zi9LFJz/+L0NH7W9woUo4D2/Ee2KOPE7yIhe/WaYFeigxqFusWOntDIJA5qEyCGBCOldePbtKQuKlekWehkq1i5LLfeAu5FmRQU2wVzME957KyKzC8pARcExSqVaZWW5fvUI5VVCGbrp1iJhzzsPEMZ4SfYQpahdbIFTHPkM851FqMYPSUvDducIwE40aaoabwmS0pNPgZ0DMl1cUf5gGeWSYyWtO9Hj/iS9QgCKa2XRUhQ2Dy1sShBnu3Wloc+gQJU+k7a0yKI7aDp2qGUdi3L1MDTIZZ4CQ9KEyXD8Zj3nG/X6j69EO5s7ext/La9NFroZvf6updgAtZXi/Ug01nFqviQ7MvKN/YmCVs+9tMjzB8I9DKZpHbK9RYxpHa4dvDWmdzyPtirouLLgtLyUtYuvh8AFZAF02HYeka7AJ8uCoPAO0K5QfrR1eM9Ag7tKsy29MtQ2lvAuR3zh73jA8Aqiw1bbLypSxIovijufOyz+7VHyEIGvcnlZwllGiUacdsLFog4rBws8Fm8r54VjDJkwXmzO6DDSfmOG+N5EfMV+FO7+V+dn2Xuy97bHH6/Almqq5jEBaB8niw1njR6HLLbFl99vzQErLpKSWiBE7tQ/0AtZqSxBLqWgYSi9gG3bYHLZ9+o1ijwEMrwLt0NIUysM="
